<?php
/**
 * ErrorCode
 *
 * PHP version 5
 *
 * @category Class
 * @package  SquareConnect
 * @author   Square Inc.
 * @license  Apache Licene v2 - http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://squareup.com/developers
 */

/**
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 3.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 *  Copyright 2016 Square, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect\Model;

use \ArrayAccess;

/**
 * ErrorCode Class Doc Comment
 *
 * @category    Class */
 // @description 
/**
 * @package     SquareConnect
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ErrorCode {
    const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
    const UNAUTHORIZED = 'UNAUTHORIZED';
    const ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED';
    const ACCESS_TOKEN_REVOKED = 'ACCESS_TOKEN_REVOKED';
    const FORBIDDEN = 'FORBIDDEN';
    const INSUFFICIENT_SCOPES = 'INSUFFICIENT_SCOPES';
    const APPLICATION_DISABLED = 'APPLICATION_DISABLED';
    const V1_APPLICATION = 'V1_APPLICATION';
    const V1_ACCESS_TOKEN = 'V1_ACCESS_TOKEN';
    const CARD_PROCESSING_NOT_ENABLED = 'CARD_PROCESSING_NOT_ENABLED';
    const BAD_REQUEST = 'BAD_REQUEST';
    const MISSING_REQUIRED_PARAMETER = 'MISSING_REQUIRED_PARAMETER';
    const INCORRECT_TYPE = 'INCORRECT_TYPE';
    const INVALID_TIME = 'INVALID_TIME';
    const INVALID_TIME_RANGE = 'INVALID_TIME_RANGE';
    const INVALID_VALUE = 'INVALID_VALUE';
    const INVALID_CURSOR = 'INVALID_CURSOR';
    const UNKNOWN_QUERY_PARAMETER = 'UNKNOWN_QUERY_PARAMETER';
    const CONFLICTING_PARAMETERS = 'CONFLICTING_PARAMETERS';
    const EXPECTED_JSON_BODY = 'EXPECTED_JSON_BODY';
    const INVALID_SORT_ORDER = 'INVALID_SORT_ORDER';
    const VALUE_TOO_LONG = 'VALUE_TOO_LONG';
    const VALUE_TOO_LOW = 'VALUE_TOO_LOW';
    const EXPECTED_BOOLEAN = 'EXPECTED_BOOLEAN';
    const EXPECTED_INTEGER = 'EXPECTED_INTEGER';
    const EXPECTED_FLOAT = 'EXPECTED_FLOAT';
    const EXPECTED_STRING = 'EXPECTED_STRING';
    const EXPECTED_OBJECT = 'EXPECTED_OBJECT';
    const EXPECTED_ARRAY = 'EXPECTED_ARRAY';
    const INVALID_ARRAY_VALUE = 'INVALID_ARRAY_VALUE';
    const INVALID_ENUM_VALUE = 'INVALID_ENUM_VALUE';
    const INVALID_CONTENT_TYPE = 'INVALID_CONTENT_TYPE';
    const INVALID_FORM_VALUE = 'INVALID_FORM_VALUE';
    const ONE_INSTRUMENT_EXPECTED = 'ONE_INSTRUMENT_EXPECTED';
    const NO_FIELDS_SET = 'NO_FIELDS_SET';
    const CARD_DECLINED = 'CARD_DECLINED';
    const CARD_EXPIRED = 'CARD_EXPIRED';
    const VERIFY_CVV_FAILURE = 'VERIFY_CVV_FAILURE';
    const VERIFY_AVS_FAILURE = 'VERIFY_AVS_FAILURE';
    const INVALID_EXPIRATION = 'INVALID_EXPIRATION';
    const INVALID_EXPIRATION_YEAR = 'INVALID_EXPIRATION_YEAR';
    const INVALID_EXPIRATION_DATE = 'INVALID_EXPIRATION_DATE';
    const INVALID_CARD = 'INVALID_CARD';
    const DELAYED_TRANSACTION_EXPIRED = 'DELAYED_TRANSACTION_EXPIRED';
    const DELAYED_TRANSACTION_CANCELED = 'DELAYED_TRANSACTION_CANCELED';
    const DELAYED_TRANSACTION_CAPTURED = 'DELAYED_TRANSACTION_CAPTURED';
    const DELAYED_TRANSACTION_FAILED = 'DELAYED_TRANSACTION_FAILED';
    const CARD_TOKEN_EXPIRED = 'CARD_TOKEN_EXPIRED';
    const CARD_TOKEN_USED = 'CARD_TOKEN_USED';
    const AMOUNT_TOO_HIGH = 'AMOUNT_TOO_HIGH';
    const UNSUPPORTED_INSTRUMENT_TYPE = 'UNSUPPORTED_INSTRUMENT_TYPE';
    const REFUND_AMOUNT_INVALID = 'REFUND_AMOUNT_INVALID';
    const REFUND_ALREADY_PENDING = 'REFUND_ALREADY_PENDING';
    const PAYMENT_NOT_REFUNDABLE = 'PAYMENT_NOT_REFUNDABLE';
    const INVALID_CARD_DATA = 'INVALID_CARD_DATA';
    const NOT_FOUND = 'NOT_FOUND';
    const REQUEST_TIMEOUT = 'REQUEST_TIMEOUT';
    const REQUEST_ENTITY_TOO_LARGE = 'REQUEST_ENTITY_TOO_LARGE';
    const UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE';
    const RATE_LIMITED = 'RATE_LIMITED';
    const NOT_IMPLEMENTED = 'NOT_IMPLEMENTED';
    const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
    

    
}

