<?php
/**
 * AddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SquareConnect
 * @author   Square Inc.
 * @license  Apache Licene v2 - http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://squareup.com/developers
 */

/**
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 3.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 *  Copyright 2016 Square, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect;

/**
 * AddressTest Class Doc Comment
 *
 * @category    Class */
// * @description 
/**
 * @package     SquareConnect
 * @author   Square Inc.
 * @license  Apache Licene v2 - http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://squareup.com/developers
 */
class AddressTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Address"
     */
    public function testAddress()
    {

    }

    /**
     * Test attribute "address_line_1"
     */
    public function testPropertyAddressLine1()
    {

    }

    /**
     * Test attribute "address_line_2"
     */
    public function testPropertyAddressLine2()
    {

    }

    /**
     * Test attribute "address_line_3"
     */
    public function testPropertyAddressLine3()
    {

    }

    /**
     * Test attribute "locality"
     */
    public function testPropertyLocality()
    {

    }

    /**
     * Test attribute "sublocality"
     */
    public function testPropertySublocality()
    {

    }

    /**
     * Test attribute "sublocality_2"
     */
    public function testPropertySublocality2()
    {

    }

    /**
     * Test attribute "sublocality_3"
     */
    public function testPropertySublocality3()
    {

    }

    /**
     * Test attribute "administrative_district_level_1"
     */
    public function testPropertyAdministrativeDistrictLevel1()
    {

    }

    /**
     * Test attribute "administrative_district_level_2"
     */
    public function testPropertyAdministrativeDistrictLevel2()
    {

    }

    /**
     * Test attribute "administrative_district_level_3"
     */
    public function testPropertyAdministrativeDistrictLevel3()
    {

    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {

    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {

    }

}
