<?php
/**
 * CashDrawerShiftTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SquareConnect
 * @author   Square Inc.
 * @license  Apache Licene v2 - http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://squareup.com/developers
 */

/**
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 3.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 *  Copyright 2016 Square, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect;

/**
 * CashDrawerShiftTest Class Doc Comment
 *
 * @category    Class */
// * @description CashDrawerShift
/**
 * @package     SquareConnect
 * @author   Square Inc.
 * @license  Apache Licene v2 - http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://squareup.com/developers
 */
class CashDrawerShiftTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CashDrawerShift"
     */
    public function testCashDrawerShift()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "event_type"
     */
    public function testPropertyEventType()
    {

    }

    /**
     * Test attribute "opened_at"
     */
    public function testPropertyOpenedAt()
    {

    }

    /**
     * Test attribute "ended_at"
     */
    public function testPropertyEndedAt()
    {

    }

    /**
     * Test attribute "closed_at"
     */
    public function testPropertyClosedAt()
    {

    }

    /**
     * Test attribute "employee_ids"
     */
    public function testPropertyEmployeeIds()
    {

    }

    /**
     * Test attribute "opening_employee_id"
     */
    public function testPropertyOpeningEmployeeId()
    {

    }

    /**
     * Test attribute "ending_employee_id"
     */
    public function testPropertyEndingEmployeeId()
    {

    }

    /**
     * Test attribute "closing_employee_id"
     */
    public function testPropertyClosingEmployeeId()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "starting_cash_money"
     */
    public function testPropertyStartingCashMoney()
    {

    }

    /**
     * Test attribute "cash_payment_money"
     */
    public function testPropertyCashPaymentMoney()
    {

    }

    /**
     * Test attribute "cash_refunds_money"
     */
    public function testPropertyCashRefundsMoney()
    {

    }

    /**
     * Test attribute "cash_paid_in_money"
     */
    public function testPropertyCashPaidInMoney()
    {

    }

    /**
     * Test attribute "cash_paid_out_money"
     */
    public function testPropertyCashPaidOutMoney()
    {

    }

    /**
     * Test attribute "expected_cash_money"
     */
    public function testPropertyExpectedCashMoney()
    {

    }

    /**
     * Test attribute "closed_cash_money"
     */
    public function testPropertyClosedCashMoney()
    {

    }

    /**
     * Test attribute "device"
     */
    public function testPropertyDevice()
    {

    }

    /**
     * Test attribute "events"
     */
    public function testPropertyEvents()
    {

    }

}
