<?php
/**
 * V1ItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SquareConnect
 * @author   Square Inc.
 * @license  Apache Licene v2 - http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://squareup.com/developers
 */

/**
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 3.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 *  Copyright 2016 Square, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect;

/**
 * V1ItemTest Class Doc Comment
 *
 * @category    Class */
// * @description V1Item
/**
 * @package     SquareConnect
 * @author   Square Inc.
 * @license  Apache Licene v2 - http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://squareup.com/developers
 */
class V1ItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "V1Item"
     */
    public function testV1Item()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {

    }

    /**
     * Test attribute "abbreviation"
     */
    public function testPropertyAbbreviation()
    {

    }

    /**
     * Test attribute "visibility"
     */
    public function testPropertyVisibility()
    {

    }

    /**
     * Test attribute "available_online"
     */
    public function testPropertyAvailableOnline()
    {

    }

    /**
     * Test attribute "master_image"
     */
    public function testPropertyMasterImage()
    {

    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {

    }

    /**
     * Test attribute "variations"
     */
    public function testPropertyVariations()
    {

    }

    /**
     * Test attribute "modifier_lists"
     */
    public function testPropertyModifierLists()
    {

    }

    /**
     * Test attribute "fees"
     */
    public function testPropertyFees()
    {

    }

    /**
     * Test attribute "taxable"
     */
    public function testPropertyTaxable()
    {

    }

}
