<?php
/**
 * V1MerchantTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SquareConnect
 * @author   Square Inc.
 * @license  Apache Licene v2 - http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://squareup.com/developers
 */

/**
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 3.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 *  Copyright 2016 Square, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect;

/**
 * V1MerchantTest Class Doc Comment
 *
 * @category    Class */
// * @description Defines the fields that are included in the response body of a request to the **RetrieveBusiness** endpoint.
/**
 * @package     SquareConnect
 * @author   Square Inc.
 * @license  Apache Licene v2 - http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://squareup.com/developers
 */
class V1MerchantTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "V1Merchant"
     */
    public function testV1Merchant()
    {

    }

    /**
     * Test attribute "errors"
     */
    public function testPropertyErrors()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "account_type"
     */
    public function testPropertyAccountType()
    {

    }

    /**
     * Test attribute "account_capabilities"
     */
    public function testPropertyAccountCapabilities()
    {

    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {

    }

    /**
     * Test attribute "language_code"
     */
    public function testPropertyLanguageCode()
    {

    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {

    }

    /**
     * Test attribute "business_name"
     */
    public function testPropertyBusinessName()
    {

    }

    /**
     * Test attribute "business_address"
     */
    public function testPropertyBusinessAddress()
    {

    }

    /**
     * Test attribute "business_phone"
     */
    public function testPropertyBusinessPhone()
    {

    }

    /**
     * Test attribute "business_type"
     */
    public function testPropertyBusinessType()
    {

    }

    /**
     * Test attribute "shipping_address_"
     */
    public function testPropertyShippingAddress_()
    {

    }

    /**
     * Test attribute "location_details"
     */
    public function testPropertyLocationDetails()
    {

    }

    /**
     * Test attribute "market_url"
     */
    public function testPropertyMarketUrl()
    {

    }

}
