<?php
/**
 * V1PaymentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SquareConnect
 * @author   Square Inc.
 * @license  Apache Licene v2 - http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://squareup.com/developers
 */

/**
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 3.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 *  Copyright 2016 Square, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect;

/**
 * V1PaymentTest Class Doc Comment
 *
 * @category    Class */
// * @description V1Payment
/**
 * @package     SquareConnect
 * @author   Square Inc.
 * @license  Apache Licene v2 - http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://squareup.com/developers
 */
class V1PaymentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "V1Payment"
     */
    public function testV1Payment()
    {

    }

    /**
     * Test attribute "errors"
     */
    public function testPropertyErrors()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "merchant_id"
     */
    public function testPropertyMerchantId()
    {

    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "creator_id"
     */
    public function testPropertyCreatorId()
    {

    }

    /**
     * Test attribute "device"
     */
    public function testPropertyDevice()
    {

    }

    /**
     * Test attribute "payment_url"
     */
    public function testPropertyPaymentUrl()
    {

    }

    /**
     * Test attribute "receipt_url"
     */
    public function testPropertyReceiptUrl()
    {

    }

    /**
     * Test attribute "inclusive_tax_money"
     */
    public function testPropertyInclusiveTaxMoney()
    {

    }

    /**
     * Test attribute "additive_tax_money"
     */
    public function testPropertyAdditiveTaxMoney()
    {

    }

    /**
     * Test attribute "tax_money"
     */
    public function testPropertyTaxMoney()
    {

    }

    /**
     * Test attribute "tip_money"
     */
    public function testPropertyTipMoney()
    {

    }

    /**
     * Test attribute "discount_money"
     */
    public function testPropertyDiscountMoney()
    {

    }

    /**
     * Test attribute "processing_fee_money"
     */
    public function testPropertyProcessingFeeMoney()
    {

    }

    /**
     * Test attribute "net_total_money"
     */
    public function testPropertyNetTotalMoney()
    {

    }

    /**
     * Test attribute "refunded_money"
     */
    public function testPropertyRefundedMoney()
    {

    }

    /**
     * Test attribute "inclusive_tax"
     */
    public function testPropertyInclusiveTax()
    {

    }

    /**
     * Test attribute "additive_tax"
     */
    public function testPropertyAdditiveTax()
    {

    }

    /**
     * Test attribute "tender"
     */
    public function testPropertyTender()
    {

    }

    /**
     * Test attribute "refunds"
     */
    public function testPropertyRefunds()
    {

    }

    /**
     * Test attribute "itemizations"
     */
    public function testPropertyItemizations()
    {

    }

}
