<?php
/**
 * V1PaymentItemizationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SquareConnect
 * @author   Square Inc.
 * @license  Apache Licene v2 - http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://squareup.com/developers
 */

/**
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 3.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 *  Copyright 2016 Square, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect;

/**
 * V1PaymentItemizationTest Class Doc Comment
 *
 * @category    Class */
// * @description V1PaymentItemization
/**
 * @package     SquareConnect
 * @author   Square Inc.
 * @license  Apache Licene v2 - http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://squareup.com/developers
 */
class V1PaymentItemizationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "V1PaymentItemization"
     */
    public function testV1PaymentItemization()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {

    }

    /**
     * Test attribute "itemization_type"
     */
    public function testPropertyItemizationType()
    {

    }

    /**
     * Test attribute "item_detail"
     */
    public function testPropertyItemDetail()
    {

    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {

    }

    /**
     * Test attribute "item_variation_name"
     */
    public function testPropertyItemVariationName()
    {

    }

    /**
     * Test attribute "total_money"
     */
    public function testPropertyTotalMoney()
    {

    }

    /**
     * Test attribute "single_quantity_money"
     */
    public function testPropertySingleQuantityMoney()
    {

    }

    /**
     * Test attribute "gross_sales_money"
     */
    public function testPropertyGrossSalesMoney()
    {

    }

    /**
     * Test attribute "discount_money"
     */
    public function testPropertyDiscountMoney()
    {

    }

    /**
     * Test attribute "net_sales_money"
     */
    public function testPropertyNetSalesMoney()
    {

    }

    /**
     * Test attribute "taxes"
     */
    public function testPropertyTaxes()
    {

    }

    /**
     * Test attribute "discounts"
     */
    public function testPropertyDiscounts()
    {

    }

    /**
     * Test attribute "modifiers"
     */
    public function testPropertyModifiers()
    {

    }

}
